/**
 * Futuristic Skills Keyboard Data
 * Each skill mapped to a keyboard key with position, metadata, and visual config
 */

export const CATEGORY_COLORS = {
  languages: '#00e5a0',
  frontend: '#60a5fa',
  backend: '#f97316',
  databases: '#a78bfa',
  tools: '#fb923c',
  cs_core: '#ec4899',
}

export const KEYBOARD_KEYS = [
  // Row 0 — Languages (top row)
  {
    id: 'cpp',
    name: 'C++',
    icon: 'C++',
    category: 'languages',
    color: '#00e5a0',
    proficiency: 85,
    years: 3,
    projects: 8,
    description: 'Systems programming, competitive programming, and performance-critical applications.',
    relatedTech: ['STL', 'Boost', 'CMake', 'GDB'],
    row: 0,
    col: 0,
  },
  {
    id: 'python',
    name: 'Python',
    icon: 'Py',
    category: 'languages',
    color: '#00e5a0',
    proficiency: 92,
    years: 4,
    projects: 15,
    description: 'Machine learning, automation, backend services, and data analysis pipelines.',
    relatedTech: ['FastAPI', 'NumPy', 'Pandas', 'PyTorch'],
    row: 0,
    col: 1,
  },
  {
    id: 'javascript',
    name: 'JavaScript',
    icon: 'JS',
    category: 'languages',
    color: '#00e5a0',
    proficiency: 95,
    years: 5,
    projects: 20,
    description: 'Full-stack web development, interactive UIs, and real-time applications.',
    relatedTech: ['ES6+', 'Node.js', 'DOM', 'WebAPIs'],
    row: 0,
    col: 2,
  },
  {
    id: 'typescript',
    name: 'TypeScript',
    icon: 'TS',
    category: 'languages',
    color: '#00e5a0',
    proficiency: 90,
    years: 3,
    projects: 12,
    description: 'Type-safe applications, scalable architectures, and enterprise codebases.',
    relatedTech: ['Generics', 'Zod', 'tRPC', 'Decorators'],
    row: 0,
    col: 3,
  },
  {
    id: 'rust',
    name: 'Rust',
    icon: 'Rs',
    category: 'languages',
    color: '#00e5a0',
    proficiency: 65,
    years: 1,
    projects: 3,
    description: 'Memory-safe systems, CLI tools, and WebAssembly modules.',
    relatedTech: ['Cargo', 'Tokio', 'WASM', 'Serde'],
    row: 0,
    col: 4,
  },

  // Row 1 — Frontend
  {
    id: 'react',
    name: 'React',
    icon: '⚛',
    category: 'frontend',
    color: '#60a5fa',
    proficiency: 95,
    years: 4,
    projects: 18,
    description: 'Component-driven UIs, hooks architecture, and complex state management.',
    relatedTech: ['Hooks', 'Context', 'Suspense', 'RSC'],
    row: 1,
    col: 0,
  },
  {
    id: 'nextjs',
    name: 'Next.js',
    icon: 'Nx',
    category: 'frontend',
    color: '#60a5fa',
    proficiency: 88,
    years: 2,
    projects: 6,
    description: 'Server-rendered apps, static sites, and full-stack React frameworks.',
    relatedTech: ['App Router', 'SSR', 'ISR', 'Vercel'],
    row: 1,
    col: 1,
  },
  {
    id: 'tailwind',
    name: 'Tailwind',
    icon: 'Tw',
    category: 'frontend',
    color: '#60a5fa',
    proficiency: 93,
    years: 3,
    projects: 14,
    description: 'Utility-first styling, responsive design systems, and rapid prototyping.',
    relatedTech: ['CSS Grid', 'Flexbox', 'JIT', 'Plugins'],
    row: 1,
    col: 2,
  },
  {
    id: 'framer',
    name: 'Framer Motion',
    icon: 'FM',
    category: 'frontend',
    color: '#60a5fa',
    proficiency: 85,
    years: 2,
    projects: 10,
    description: 'Fluid animations, gesture interactions, and cinematic UI transitions.',
    relatedTech: ['Gestures', 'Layout', 'Variants', 'SVG'],
    row: 1,
    col: 3,
  },
  {
    id: 'threejs',
    name: 'Three.js',
    icon: '3J',
    category: 'frontend',
    color: '#60a5fa',
    proficiency: 75,
    years: 1,
    projects: 4,
    description: '3D visualizations, immersive web experiences, and WebGL applications.',
    relatedTech: ['WebGL', 'Shaders', 'GLTF', 'PostFX'],
    row: 1,
    col: 4,
  },

  // Row 2 — Backend + Databases
  {
    id: 'nodejs',
    name: 'Node.js',
    icon: 'No',
    category: 'backend',
    color: '#f97316',
    proficiency: 92,
    years: 4,
    projects: 16,
    description: 'REST APIs, real-time servers, microservices, and event-driven architectures.',
    relatedTech: ['Express', 'Streams', 'Workers', 'NPM'],
    row: 2,
    col: 0,
  },
  {
    id: 'express',
    name: 'Express',
    icon: 'Ex',
    category: 'backend',
    color: '#f97316',
    proficiency: 90,
    years: 3,
    projects: 12,
    description: 'RESTful APIs, middleware pipelines, and authentication systems.',
    relatedTech: ['Middleware', 'JWT', 'CORS', 'Router'],
    row: 2,
    col: 1,
  },
  {
    id: 'fastapi',
    name: 'FastAPI',
    icon: 'Fa',
    category: 'backend',
    color: '#f97316',
    proficiency: 80,
    years: 2,
    projects: 5,
    description: 'High-performance Python APIs with async support and auto-documentation.',
    relatedTech: ['Pydantic', 'Async', 'Swagger', 'Uvicorn'],
    row: 2,
    col: 2,
  },
  {
    id: 'postgresql',
    name: 'PostgreSQL',
    icon: 'Pg',
    category: 'databases',
    color: '#a78bfa',
    proficiency: 85,
    years: 3,
    projects: 10,
    description: 'Relational databases, complex queries, indexing strategies, and data modeling.',
    relatedTech: ['SQL', 'Prisma', 'Indexing', 'Joins'],
    row: 2,
    col: 3,
  },
  {
    id: 'mongodb',
    name: 'MongoDB',
    icon: 'Mg',
    category: 'databases',
    color: '#a78bfa',
    proficiency: 82,
    years: 2,
    projects: 8,
    description: 'Document databases, flexible schemas, and aggregation pipelines.',
    relatedTech: ['Mongoose', 'Atlas', 'Aggregation', 'BSON'],
    row: 2,
    col: 4,
  },

  // Row 3 — Tools + Redis
  {
    id: 'git',
    name: 'Git',
    icon: 'Gi',
    category: 'tools',
    color: '#fb923c',
    proficiency: 94,
    years: 5,
    projects: 25,
    description: 'Version control, branching strategies, collaborative workflows, and CI/CD.',
    relatedTech: ['GitHub', 'Rebase', 'Hooks', 'Bisect'],
    row: 3,
    col: 0,
  },
  {
    id: 'docker',
    name: 'Docker',
    icon: 'Dk',
    category: 'tools',
    color: '#fb923c',
    proficiency: 80,
    years: 2,
    projects: 7,
    description: 'Containerization, multi-stage builds, and deployment orchestration.',
    relatedTech: ['Compose', 'Dockerfile', 'Volumes', 'Networks'],
    row: 3,
    col: 1,
  },
  {
    id: 'linux',
    name: 'Linux',
    icon: 'Lx',
    category: 'tools',
    color: '#fb923c',
    proficiency: 85,
    years: 4,
    projects: 15,
    description: 'System administration, shell scripting, and server management.',
    relatedTech: ['Bash', 'SSH', 'Systemd', 'Cron'],
    row: 3,
    col: 2,
  },
  {
    id: 'redis',
    name: 'Redis',
    icon: 'Rd',
    category: 'databases',
    color: '#a78bfa',
    proficiency: 72,
    years: 1,
    projects: 4,
    description: 'In-memory caching, session management, and real-time data structures.',
    relatedTech: ['Pub/Sub', 'Streams', 'Lua', 'Sentinel'],
    row: 3,
    col: 3,
  },
  {
    id: 'figma',
    name: 'Figma',
    icon: 'Fi',
    category: 'tools',
    color: '#fb923c',
    proficiency: 78,
    years: 3,
    projects: 12,
    description: 'UI/UX design, prototyping, design systems, and developer handoff.',
    relatedTech: ['AutoLayout', 'Components', 'Dev Mode', 'Plugins'],
    row: 3,
    col: 4,
  },
]

// CS Fundamentals as a "command strip"
export const CS_COMMANDS = [
  { id: 'dsa', name: 'DSA', fullName: 'Data Structures & Algorithms' },
  { id: 'os', name: 'OS', fullName: 'Operating Systems' },
  { id: 'dbms', name: 'DBMS', fullName: 'Database Management Systems' },
  { id: 'cn', name: 'CN', fullName: 'Computer Networks' },
  { id: 'ood', name: 'OOD', fullName: 'Object-Oriented Design' },
  { id: 'sd', name: 'SD', fullName: 'System Design' },
]

// Keyboard layout dimensions
export const KEYBOARD_LAYOUT = {
  rows: 4,
  cols: 5,
  keyWidth: 1.4,
  keyDepth: 1.4,
  keyHeight: 0.45,
  gapX: 0.18,
  gapZ: 0.18,
  chassisPadding: 0.6,
  chassisHeight: 0.25,
}

// Get skill by id
export function getSkillById(id) {
  return KEYBOARD_KEYS.find(k => k.id === id) || null
}

// Get skills by category
export function getSkillsByCategory(category) {
  return KEYBOARD_KEYS.filter(k => k.category === category)
}

// Get neighboring keys (for chain-lighting effects)
export function getNeighborKeys(row, col) {
  return KEYBOARD_KEYS.filter(k => {
    const dr = Math.abs(k.row - row)
    const dc = Math.abs(k.col - col)
    return (dr <= 1 && dc <= 1) && !(dr === 0 && dc === 0)
  })
}
